[project]
name = "towers-breaker"
version = "0.1.0"
description = "Plays Towers Breaker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pudb>=2024.1.3",
    "pytest>=8.3.5",
    "pytest-dotenv>=0.5.2",
    "ruff>=0.11.4",
]
