[project]
name = "leetcode-0383"
version = "0.1.0"
description = "Ransom Note"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pudb>=2025.1.5",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
    "ty>=0.0.66",
]
[tool.pytest.ini_options]
pythonpath=[".", "../../_common"]
log_cli="true"
log_level="WARNING"
