[project]
name = "leetcode-2095"
version = "0.1.0"
description = "Delete the Middle Node of a Linked List"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.1",
    "ty>=0.0.65",
]
[tool.pytest.ini_options]
pythonpath=[".", "../../_common"]
log_cli="true"
log_level="DEBUG"
