[project]
name = "leetcode-2011"
version = "0.1.0"
description = "Final Value of Variable After Performing Operations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pudb>=2025.1.5",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
    "ty>=0.0.80",
]

[tool.pytest.ini_options]
pythonpath = [".", "../../_common"]

log_cli = true
log_cli_level = "WARNING"
log_file = "/tmp/leetcode-2011.log"
log_file_level = "DEBUG"
