[project]
name = "caesar-cipher"
version = "0.1.0"
description = "Shift letters cipher"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ipython>=9.1.0",
    "pudb>=2024.1.3",
    "pytest>=8.3.5",
    "pytest-dotenv>=0.5.2",
    "ruff>=0.11.4",
]
